# Generated by Django 4.2.5 on 2023-10-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_whitelisted',
            field=models.BooleanField(default=False),
        ),
    ]
