# Generated by Django 4.2.5 on 2023-10-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_component_pipeline_pipelinecomponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
