# Generated by Django 4.2.5 on 2023-11-01 10:10

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pipeline_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='components',
        ),
        migrations.AddField(
            model_name='component',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='description',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='function_name',
            field=models.CharField(default='temp', validators=[core.validators.validate_function_name]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipeline',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(),
        ),
        migrations.DeleteModel(
            name='PipelineComponent',
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.component'),
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pipeline'),
        ),
    ]
