# Generated by Django 4.2.5 on 2023-11-02 18:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_componentinstance_remove_pipeline_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinstance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.JSONField(default=core.models.Component.component_description_default),
        ),
    ]
