# Generated by Django 4.2.5 on 2023-11-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_oaichat'),
        ('oai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oaichat',
            name='chatcmpl',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oai.chatcmplrequest'),
        ),
        migrations.AddField(
            model_name='oaichat',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pipeline'),
        ),
    ]
