# Generated by Django 4.2.5 on 2023-11-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_oaichat_chatcmpl_oaichat_user_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oaichat',
            old_name='is_first',
            new_name='clear_history',
        ),
    ]
