# Generated by Django 4.2.5 on 2023-11-04 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_is_first_oaichat_clear_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OaiChat',
            new_name='Chat',
        ),
    ]
