# Generated by Django 4.2.5 on 2023-11-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_oaichat_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='User', max_length=255),
            preserve_default=False,
        ),
    ]
