# Generated by Django 4.2.5 on 2023-11-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_chat_api_message_alter_chat_user_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='state',
            field=models.JSONField(default=dict),
        ),
    ]
