# Generated by Django 4.2.5 on 2023-11-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pipeline_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='is_safe',
            field=models.BooleanField(default=False),
        ),
    ]
