# Generated by Django 4.2.5 on 2023-11-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pipeline_is_safe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='clear_history',
        ),
    ]
