# Generated by Django 4.2.5 on 2023-11-30 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_chat_clear_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinstance',
            name='component',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.component'),
        ),
    ]
