# Generated by Django 4.2.5 on 2023-12-04 16:54

import core.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_componentinstance_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='is_safe',
        ),
        migrations.AddField(
            model_name='component',
            name='arguments',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='component',
            name='return_type',
            field=models.CharField(choices=[('string', 'string'), ('number', 'number'), ('boolean', 'boolean'), ('list', 'list'), ('dictionary', 'dictionary'), ('none', 'none')], default=core.enums.ReturnType['DICTIONARY'], max_length=255),
        ),
    ]
