# Generated by Django 4.2.5 on 2023-12-05 06:35

import core.enums
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_pipeline_is_safe_component_arguments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='description',
            field=models.JSONField(default=core.models.Pipeline.pipeline_description_default),
        ),
        migrations.AlterField(
            model_name='component',
            name='return_type',
            field=models.CharField(choices=[('string', 'string'), ('number', 'number'), ('boolean', 'boolean'), ('list', 'list'), ('dictionary', 'dictionary'), ('none', 'none')], default=core.enums.ReturnType['NONE'], max_length=255),
        ),
    ]
