# Generated by Django 4.2.5 on 2023-12-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pipeline_description_alter_component_return_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
