# Generated by Django 4.2.5 on 2023-12-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_component_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
