# Generated by Django 4.2.5 on 2023-12-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_pipeline_response_alter_component_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="api_message",
            new_name="resp_message",
        )
    ]
