# Generated by Django 4.2.5 on 2023-12-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_api_message_chat_resp_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='resp_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_message',
            field=models.TextField(blank=True),
        ),
    ]
