# Generated by Django 4.2.5 on 2023-12-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_chat_resp_message_alter_chat_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='exit_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
