# Generated by Django 4.2.5 on 2023-12-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_user_api_key_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='encrypted_key',
            field=models.TextField(default='THIS IS A TEMPORARY KEY'),
        ),
    ]
