# Generated by Django 4.2.5 on 2023-12-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_apikey_encrypted_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-created_at']},
        ),
    ]
