# Generated by Django 4.2.5 on 2023-11-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_oaichat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatcmpl',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('created', models.PositiveIntegerField()),
                ('model', models.CharField()),
                ('object', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='FunctionCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arguments', models.CharField()),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_tokens', models.PositiveIntegerField()),
                ('prompt_tokens', models.PositiveIntegerField()),
                ('total_tokens', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField()),
                ('name', models.CharField(blank=True, null=True)),
                ('role', models.CharField()),
                ('function_call', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oai.functioncall')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_reason', models.CharField(choices=[('stop', 'stop'), ('length', 'length'), ('content_filter', 'content_filter'), ('function_call', 'function_call')])),
                ('index', models.PositiveIntegerField()),
                ('chatcmpl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oai.chatcmpl')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oai.message')),
            ],
        ),
        migrations.CreateModel(
            name='ChatcmplRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.JSONField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.component')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oai.chatcmpl')),
            ],
        ),
        migrations.AddField(
            model_name='chatcmpl',
            name='usage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oai.usage'),
        ),
    ]
