# Generated by Django 4.2.5 on 2023-11-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcmpl',
            name='object',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='functioncall',
            name='arguments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='functioncall',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('system', 'system'), ('user', 'user'), ('assistant', 'assistant'), ('function', 'function')]),
        ),
    ]
