# Generated by Django 4.2.5 on 2024-01-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0030_alter_chat_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiProRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.JSONField()),
                ('response', models.JSONField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.component')),
            ],
        ),
    ]
